MODEL_CONFIGS = {'lwdetr_large_60e_coco':{
    'batch_size': 2,
    'encoder': 'vit_small',
    'vit_encoder_num_layers': 10,
    'window_block_indexes': [0, 1, 3, 6, 7, 9],
    'out_feature_indexes': [2, 4, 5, 9],
    'dec_layers': 3,
    'group_detr': 13,
    'two_stage': True,
    'projector_scale': ['P3', 'P5'],
    'hidden_dim': 384,
    'sa_nheads': 12,
    'ca_nheads': 24,
    'dec_n_points': 4,
    'bbox_reparam': True,
    'lite_refpoint_refine': True,
    'num_select': 300,
    'dataset_file': 'coco',
    'square_resize_div_64': True,
    'use_ema': True,
    'eval': True,
    },
    'lwdetr_small_60e_coco':{
    'encoder': 'vit_tiny',
    'vit_encoder_num_layers': 10,
    'window_block_indexes': [0, 1, 3, 6, 7, 9],
    'out_feature_indexes': [2, 4, 5, 9],
    'dec_layers': 3,
    'group_detr': 13,
    'two_stage': True,
    'projector_scale': 'P4',
    'hidden_dim': 256,
    'sa_nheads': 8,
    'ca_nheads': 16,
    'dec_n_points': 2,
    'bbox_reparam': True,
    'lite_refpoint_refine': True,
    'num_select': 300,
    'confidence_threshold': 0.5,
    },
    'lwdetr_xlarge_60e_coco':{
        'batch_size': 1,
        'encoder': 'vit_base',
        'vit_encoder_num_layers': 10,
        'window_block_indexes': [0, 1, 3, 6, 7, 9],
        'out_feature_indexes': [2, 4, 5, 9],
        'dec_layers': 3,
        'group_detr': 13,
        'two_stage': True,
        'projector_scale': ['P3', 'P5'],
        'hidden_dim': 384,
        'sa_nheads': 12,
        'ca_nheads': 24,
        'dec_n_points': 4,
        'bbox_reparam': True,
        'lite_refpoint_refine': True,
        'num_select': 300,
        'square_resize_div_64': True,
        'use_ema': True,
        'eval': True,
        },
    'lwdetr_medium_60e_coco':{
        'batch_size': 1,
        'encoder': 'vit_small',
        'vit_encoder_num_layers': 10,
        'window_block_indexes': [0, 1, 3, 6, 7, 9],
        'out_feature_indexes': [2, 4, 5, 9],
        'dec_layers': 3,
        'group_detr': 13,
        'two_stage': True,
        'projector_scale': ['P4'],
        'hidden_dim': 256,
        'sa_nheads': 8,
        'ca_nheads': 16,
        'dec_n_points': 2,
        'bbox_reparam': True,
        'lite_refpoint_refine': True,
        'num_select': 300,
        'square_resize_div_64': True,
        'use_ema': True,
        'eval': True,}
    }
